---
services:
  web:
    build:
      context: .
    environment:
    - LDAP_UPDATE_USER=${USER}
    env_file:
    - .env
    volumes:
    - .:/var/www
    ports:
    - "3000:80"
    depends_on:
    - db

  db:
    image: mariadb:12.3
    env_file:
    - .env
    volumes:
    - "db:/var/lib/mysql"
    - "./db/init-data-tables.sql:/docker-entrypoint-initdb.d/init-data.sql"

  apache-exporter:
    image: bitnami/apache-exporter:latest@sha256:9f4309c873ac3ba31f9c05646908a82fe7a34165701e4907330af5e9ac0e793a
    command: [ "--scrape_uri=http://web:81/server-status?auto" ]
    profiles:
      - monitoring

volumes:
  db:
