---
services:
  web:
    build:
      context: .
    environment:
    - LDAP_UPDATE_USER=${USER}
    env_file:
    - .env
    volumes:
    - .:/var/www
    ports:
    - "3000:80"
    depends_on:
    - db

  db:
    image: mariadb:12.3
    env_file:
    - .env
    volumes:
    - "db:/var/lib/mysql"
    - "./db/init-data-tables.sql:/docker-entrypoint-initdb.d/init-data.sql"

  apache-exporter:
    image: bitnami/apache-exporter:latest@sha256:e8251cd0660f6a795d3fd5984a24e6b5734340611a69dee6b1fea371d6d9283d
    command: [ "--scrape_uri=http://web:81/server-status?auto" ]
    profiles:
      - monitoring

volumes:
  db:
