---
services:
  web:
    build:
      context: .
    environment:
    - LDAP_UPDATE_USER=${USER}
    env_file:
    - .env
    volumes:
    - .:/var/www
    ports:
    - "3000:80"
    depends_on:
    - db

  db:
    image: mariadb:11.5
    env_file:
    - .env
    volumes:
    - "db:/var/lib/mysql"
    - "./db/init-data-tables.sql:/docker-entrypoint-initdb.d/init-data.sql"

  apache-exporter:
    image: bitnami/apache-exporter:latest@sha256:706ec12528bad17ee1a41fb7c6e002b076f123392cdbac54651ae8f6f907bebb
    command: [ "--scrape_uri=http://web:81/server-status?auto" ]
    profiles:
      - monitoring

volumes:
  db:
